import type { Article, Topic } from "@/content/types";

/**
 * The knowledge hub.
 *
 * Evergreen guidance on doing project work well. This is the surface that feeds
 * Google Discover (`Google Discover.txt`) and it is the one place on the site
 * where the content is written by us rather than generated by the product
 * working — so it has to earn its place.
 *
 * Each article answers a question a student actually asks, in the register of
 * someone who has supervised the work rather than someone optimising for a
 * keyword.
 */
export const articles: Article[] = [
  {
    slug: "how-to-choose-a-final-year-project",
    title: "How to choose a final-year project you can finish",
    description:
      "Most final-year projects fail on scope, not ability. A practical guide to picking a problem you can actually complete in one or two semesters.",
    section: "Getting started",
    author: "Nexivora",
    publishedOn: "2026-06-12",
    updatedOn: "2026-08-30",
    readingMinutes: 8,
    keywords: [
      "final year project",
      "project selection",
      "project scope",
      "engineering project ideas",
    ],
    body: `Most final-year projects that go badly do not go badly because the team lacked the ability. They go badly because the project was the wrong size, and that was decided in the first two weeks.

## Start from a problem you can see

The strongest projects we see start from something the team has personally observed. A canteen that throws away food, a lab register nobody can read, an irrigation timer that runs in the rain.

This matters for a practical reason: if you can see the problem, you can measure it, and if you can measure it you can prove your project did something. A project taken from a list of ideas usually has no accessible baseline, so at the end you cannot say whether it worked.

## Scope to one semester, then add

The reliable test: **could you finish a crude, working version in six weeks?** If not, the project is too big, regardless of how interesting it is.

A working crude version beats an ambitious incomplete one on every axis that matters — you can test it, you can show it, and you can build the ambitious version on top of it if time allows.

- Write down what "done" means before you start
- Cut the feature you are least sure about, immediately
- Plan for the prototype to fail twice, because it will

## Check whether it has been done in your own college

This is the step almost everyone skips. Search your college's project archive before you commit. You will find one of three things:

1. Nobody has done it — proceed.
2. Someone has done it badly — that is a good project, and say so explicitly.
3. Someone has done it well — **build on it**. This is better than starting fresh, not worse.

Building on a previous group's work is not a lesser project. It is how research actually works, and it means you spend your semester on the new part rather than rebuilding the sensing rig that already exists.

## Pick something you will still care about in month four

Enthusiasm carries the first six weeks. After that the project is debugging, writing and testing, and interest is what gets you through it. Choose accordingly.`,
    related: [
      "writing-a-project-report-that-is-actually-read",
      "what-makes-a-project-worth-publishing",
    ],
  },
  {
    slug: "writing-a-project-report-that-is-actually-read",
    title: "Writing a project report that is actually read",
    description:
      "Section by section, what belongs in a project report and what does not — written from the perspective of the person evaluating it.",
    section: "Documentation",
    author: "Nexivora",
    publishedOn: "2026-06-28",
    readingMinutes: 10,
    keywords: [
      "project report",
      "how to write project report",
      "methodology section",
      "engineering documentation",
    ],
    body: `A project report is read by someone with twenty others to get through. Everything below follows from that.

## The problem statement is not the introduction

The most common failure is a problem statement that describes a topic rather than a problem. "IoT is an emerging field with applications in agriculture" is a topic. "The campus farm irrigates on a fixed timer and waters during rainfall" is a problem.

A problem statement should name who has the problem, what it costs them, and how you know. If you cannot say how you know, that is the first thing to go and find out.

## Background research means what others tried and why it did not fit

Not a literature summary. The useful version is: here are the two or three approaches that already exist, here is what each does well, here is the specific reason none of them solves our case.

If every existing approach would have worked, the honest conclusion is that you should have used one.

## Methodology should let someone repeat you

The test is simple: could a competent person in your department reproduce your result from this section alone? Numbered steps, actual parameters, and the things you calibrated.

Include the decisions that could have gone another way. "We split the data chronologically rather than randomly, because a random split on a time series leaks future information" tells the reader you understood the problem. "We split 80/20" does not.

## Results are numbers with conditions attached

Report what you measured, under what conditions, with what sample size. Then report the cases where it did worse.

A result with a stated limitation is more credible than one without, not less. Evaluators notice the absence of limitations and assume you did not look.

## Conclusion is not a summary

The summary is the abstract. The conclusion is what you now believe that you did not believe at the start, and what remains unresolved. If the conclusion could have been written before the project began, it is not a conclusion.`,
    related: ["how-to-choose-a-final-year-project", "what-makes-a-project-worth-publishing"],
  },
  {
    slug: "surviving-group-project-free-riding",
    title: "When someone in your group is not contributing",
    description:
      "The most common and least discussed problem in group coursework, and the approaches that actually change the outcome.",
    section: "Working in teams",
    author: "Nexivora",
    publishedOn: "2026-07-15",
    readingMinutes: 7,
    keywords: ["group project", "free riding", "team contribution", "student teamwork"],
    body: `Almost every student has been in a group where one person did very little and received the same grade. It is the most universally felt problem in coursework and the one least often addressed directly.

## Why it persists

Three reasons, and none of them is that faculty do not care:

1. **Contribution is invisible.** Work happens in a chat and a shared folder. By submission there is no record of who did what.
2. **Reporting it feels like betrayal.** Students consistently choose an unfair grade over an uncomfortable conversation.
3. **By the time it is obvious, it is too late.** Raised in the final week, there is nothing anyone can do.

## What actually helps

**Make contribution visible early, and to everyone.** Not as surveillance — as feedback. A group that can see, in week three, that one member has closed no tasks will usually correct itself without anyone escalating. The same information delivered in week fourteen is only useful for allocating blame.

**Assign ownership, not tasks.** "Rohit owns the sensor calibration" creates a clear boundary. "We will all work on the hardware" does not, and it is where contribution quietly disappears.

**Have the conversation in week four.** Not about effort or commitment — about the specific thing that did not happen. It is a much easier conversation early, and it works far more often than people expect.

## If it does not resolve

Raise it with your supervisor before the final month, with specifics rather than an impression. A supervisor who is told in week six can restructure the work. A supervisor told in week fifteen can only adjust a grade, which helps nobody learn anything.

Keep a record as you go — not to build a case, but because reconstructing four months of work from memory in an argument is impossible and unpleasant.`,
    related: ["how-to-choose-a-final-year-project"],
  },
  {
    slug: "what-makes-a-project-worth-publishing",
    title: "What makes a student project worth publishing",
    description:
      "Not every project should be public. A guide to which ones benefit from publication and how to prepare them for it.",
    section: "Publishing",
    author: "Nexivora",
    publishedOn: "2026-07-29",
    readingMinutes: 6,
    keywords: ["publish student project", "project portfolio", "open project documentation"],
    body: `Publishing a project makes it findable, citable and something you can point an employer at. It is also permanent, so it is worth deciding deliberately.

## Publish if any of these is true

- **It produced a measurement nobody had.** Even a modest project that quantified something previously unmeasured is genuinely useful to the next person.
- **It failed in an instructive way.** A documented failure with a clear cause is more useful to a future team than a vague success.
- **Someone could build on it.** If your calibration, dataset or design would save another group a month, publishing it is the whole point.

## Do not publish if

- It contains personal data of identifiable people without their consent.
- It is patentable and not yet filed — use an embargo instead, which lets the work be cited without being disclosed.
- The result is a claim you cannot support. A published overclaim follows you.

## Before you publish

Write the abstract last, and write it for someone outside your department. If you cannot explain what you did in three sentences without jargon, the report probably needs work too.

Check that every number in the results has its conditions attached, and that the limitations section is honest. The point of publishing is that other people rely on it.`,
    related: ["writing-a-project-report-that-is-actually-read"],
  },
  {
    slug: "sdg-alignment-for-student-projects",
    title: "Mapping a project to the SDGs, honestly",
    description:
      "How to map project work to the Sustainable Development Goals without the tenuous claims that make the exercise meaningless.",
    section: "Impact",
    author: "Nexivora",
    publishedOn: "2026-08-08",
    readingMinutes: 6,
    keywords: [
      "SDG student projects",
      "sustainable development goals",
      "SDG mapping",
      "NAAC SDG reporting",
    ],
    body: `Institutions now report on how student work contributes to the Sustainable Development Goals. The exercise is useful when the mapping is honest and worthless when it is not.

## The failure mode

Claiming six goals for a project that touches one. A water-monitoring project is SDG 6, plausibly 3 and 11. It is not SDG 5, and tagging it so makes every other tag on the platform less trustworthy.

Over-tagging is not harmless. It is the reason SDG reporting has a credibility problem, and a report where everything claims everything conveys no information.

## A workable test

For each goal you are considering, complete this sentence with something specific:

> *This project contributes to [goal] because it [verb] [measurable thing] for [whom].*

If you cannot fill it in with a measurable thing, drop the goal.

## Primary and secondary

Most projects have **one** primary goal and one or two genuine secondary ones. Tag it that way. A project reducing irrigation water use is primarily SDG 6; secondarily 2, because water efficiency affects yield; arguably 13. Three is a defensible claim; six is not.

## Why it matters beyond the report

A student searching for work related to clean water should find projects that are genuinely about clean water. Every tenuous tag makes that search worse for the next person.`,
    related: ["what-makes-a-project-worth-publishing"],
  },
  {
    slug: "keeping-a-project-archive-your-college-can-use",
    title: "Why colleges lose their own project work",
    description:
      "Most institutions cannot find last year's projects. What that costs students and faculty, and the three properties a usable archive needs.",
    section: "For institutions",
    author: "Nexivora",
    publishedOn: "2026-08-20",
    readingMinutes: 7,
    keywords: [
      "project archive",
      "institutional memory",
      "NAAC documentation",
      "college project records",
    ],
    body: `Ask a department for the best project it produced four years ago. In most institutions the answer involves a hard drive, a former faculty member, and eventually a shrug.

## What that costs

**Students rebuild.** A group spends six weeks reconstructing a sensing rig an earlier group already built and documented, because they had no way to know it existed.

**Nothing compounds.** Every batch starts from zero, so the fifth cohort's work is no more advanced than the first's. In a functioning research group that would be unthinkable.

**Accreditation becomes an archaeology exercise.** Every NAAC or NBA cycle, a committee reconstructs project evidence from email attachments and printed reports, and it takes weeks of faculty time.

## What an archive actually needs

A folder of PDFs is not an archive. Three properties make the difference:

1. **Searchable by content, not filename.** If you cannot find the project by describing the problem it solved, it is not findable.
2. **A stable identifier.** A project that can be cited needs an address that does not change when someone reorganises a drive.
3. **Recorded lineage.** The valuable question is not only "what did they do" but "what did the next group do with it". Without a recorded parent-child relationship, that chain is invisible.

## The compounding effect

An archive with these properties changes what a project *is*. A group can start from an existing result rather than from nothing, and the department's fourth-year work gets measurably more advanced over time.

That is not a documentation improvement. It is the difference between a department that accumulates knowledge and one that does not.`,
    related: ["what-makes-a-project-worth-publishing", "how-to-choose-a-final-year-project"],
  },
];

export const articleBySlug = Object.fromEntries(articles.map((a) => [a.slug, a])) as Record<
  string,
  Article
>;

export const knowledgeSections = [...new Set(articles.map((a) => a.section))];

/**
 * Editorial copy for the topic hub pages.
 *
 * Hub pages must have genuine editorial content — generating a thin shell per
 * taxonomy node is exactly the doorway-page pattern `technical and Spam.txt`
 * prohibits. Topics without an entry here render their taxonomy summary and the
 * project list only, which is honest rather than padded.
 */
export const topicEditorial: Record<string, Pick<Topic, "intro" | "faqs">> = {
  "ai-ml": {
    intro:
      "Machine-learning projects fail evaluation more often than they fail technically. The usual cause is a validation score that does not survive contact with how the data was split, or a model trained on a dataset that could never exist at deployment. The projects here that hold up are the ones where the evaluation was designed before the model.",
    faqs: [
      {
        question: "Do I need a large dataset for a final-year ML project?",
        answer:
          "Usually not. A small dataset you collected and understand beats a large one you downloaded and cannot explain. What matters is that the evaluation is honest — chronological splits for time series, participant-level splits when the same person appears more than once.",
      },
      {
        question: "Is it acceptable to use a pre-trained model?",
        answer:
          "Yes, and it is usually the right choice. The contribution then has to be somewhere else: the dataset, the evaluation, the deployment constraint, or the problem framing. Fine-tuning an existing model and reporting its benchmark score is not a project.",
      },
    ],
  },
  sustainability: {
    intro:
      "Sustainability projects live or die on measurement. A design that plausibly saves water or energy is not a result; a measured comparison against a baseline is. The strongest work in this domain usually spends more effort on instrumenting the baseline than on the intervention.",
    faqs: [
      {
        question: "How do I establish a baseline if nothing is currently measured?",
        answer:
          "Measure it first. A month of logging the existing system before you change anything is not lost time — it is the only thing that will let you state a result at the end. Several projects here found the baseline measurement was the more valuable output.",
      },
    ],
  },
  healthcare: {
    intro:
      "Healthcare projects carry a duty the others do not: a tool that is wrong can cause harm rather than inconvenience. The work here is expected to state its limitations plainly, to distinguish screening from diagnosis, and to report performance across subgroups rather than only in aggregate.",
    faqs: [
      {
        question: "Do I need ethics approval for a health project?",
        answer:
          "If it involves human participants or their data, almost certainly yes. Start the process early — it commonly takes longer than students expect, and work done before approval cannot be used.",
      },
    ],
  },
  "hardware-iot": {
    intro:
      "Hardware projects are decided by the parts nobody puts in the presentation: the enclosure, the power budget, and what happens in the monsoon. Most of the failures documented in this domain are mechanical or environmental rather than electronic.",
  },
  "social-impact": {
    intro:
      "The recurring lesson in this domain is that the technical problem is rarely the binding constraint. Adoption, trust and explanation usually are — several projects here found that a solution nobody could explain to the affected person was a solution nobody used.",
  },
  education: {
    intro:
      "Education projects have an unusually accessible evaluation: the students and faculty you are building for are in the same building. The work here that stands out is the work that actually asked them, before building.",
  },
  software: {
    intro:
      "The most common weakness in software projects is that they solve a problem nobody confirmed exists. The strongest here started by observing the current process for a week — and in more than one case discovered the real problem was different from the assumed one.",
  },
  research: {
    intro:
      "Research-shaped projects are judged on method rather than outcome. A negative result with sound methodology is a contribution; a positive result from a flawed protocol is not.",
  },
};
