import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * REAL BYTES FOR THE SEEDED FILES.
 *
 * The seed creates 90 `FileAsset` rows. Until this module existed it wrote no
 * objects to go with them, so every file in the demo world returned 404 when
 * anybody clicked it — the route was behaving correctly (a missing object is a
 * 404) and the demo was lying.
 *
 * That is worth more than a cosmetic fix. A file store with rows and no bytes
 * makes acceptance criterion 5 untestable against real data: "a file uploaded
 * by group A returns 404 to a member of group B" proves nothing when it returns
 * 404 to everybody. `check-workspace.mjs` found this by asserting the positive
 * control first, which is the entire reason a denial suite needs one.
 *
 * The content is generated, small and plausible — a real PDF header, real CSV
 * rows, real Markdown. Not because anybody reads it, but because the file route
 * verifies magic bytes on the way *in* and a demo whose own files would fail
 * their own upload check is the kind of inconsistency that surfaces in a
 * presentation.
 */

const PDF = (title: string) =>
  Buffer.from(
    `%PDF-1.7\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n` +
      `% ${title}\n% Placeholder document generated by the Nexivora seed.\n` +
      `trailer\n<< /Root 1 0 R >>\n%%EOF\n`,
    "utf8",
  );

const CSV = () => {
  const rows = ["timestamp,sensor_id,moisture_pct,temperature_c"];
  for (let i = 0; i < 60; i += 1) {
    const moisture = (28 + Math.sin(i / 6) * 9).toFixed(1);
    const temperature = (24 + Math.cos(i / 8) * 5).toFixed(1);
    rows.push(
      `2026-03-${String((i % 28) + 1).padStart(2, "0")}T06:00:00Z,S-${(i % 4) + 1},${moisture},${temperature}`,
    );
  }
  return Buffer.from(rows.join("\n") + "\n", "utf8");
};

const MARKDOWN = (title: string) =>
  Buffer.from(
    `# ${title}\n\n` +
      `Placeholder notes generated by the Nexivora seed.\n\n` +
      `## Sources reviewed\n\n- Low-cost soil moisture sensing, a survey\n` +
      `- Canal scheduling under constrained supply\n- Field deployment failure modes\n\n` +
      `## Open questions\n\n1. Calibration drift over a monsoon season\n2. Power budget for a remote node\n`,
    "utf8",
  );

const NOTEBOOK = () =>
  Buffer.from(
    JSON.stringify(
      {
        cells: [
          {
            cell_type: "markdown",
            metadata: {},
            source: ["# Results analysis\\n", "Placeholder notebook from the Nexivora seed."],
          },
          {
            cell_type: "code",
            execution_count: 1,
            metadata: {},
            outputs: [],
            source: [
              "import pandas as pd\\n",
              "df = pd.read_csv('field-data-week-1.csv')\\n",
              "df.describe()",
            ],
          },
        ],
        metadata: { kernelspec: { display_name: "Python 3", language: "python", name: "python3" } },
        nbformat: 4,
        nbformat_minor: 5,
      },
      null,
      1,
    ),
    "utf8",
  );

/**
 * A minimal but structurally valid ZIP: one stored (uncompressed) entry.
 *
 * Hand-built rather than pulled from a library — the seed has no dependencies
 * and this is forty bytes of header format. It matters that it is real: the
 * upload path identifies ZIP-family files by the `PK\x03\x04` signature, and a
 * demo file that would be rejected by our own validator is a trap for whoever
 * next tests the upload flow using a seeded file as their example.
 */
function ZIP(): Buffer {
  const name = Buffer.from("readme.txt", "utf8");
  const content = Buffer.from("Placeholder archive from the Nexivora seed.\n", "utf8");

  // CRC-32 of the content, computed rather than faked: an archive with a wrong
  // checksum opens in nothing.
  let crc = ~0;
  for (const byte of content) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  crc = ~crc >>> 0;

  const local = Buffer.alloc(30);
  local.writeUInt32LE(0x04034b50, 0); // PK\x03\x04
  local.writeUInt16LE(20, 4); // version needed
  local.writeUInt16LE(0, 6); // flags
  local.writeUInt16LE(0, 8); // stored, no compression
  local.writeUInt32LE(crc, 14);
  local.writeUInt32LE(content.length, 18);
  local.writeUInt32LE(content.length, 22);
  local.writeUInt16LE(name.length, 26);

  const central = Buffer.alloc(46);
  central.writeUInt32LE(0x02014b50, 0);
  central.writeUInt16LE(20, 4);
  central.writeUInt16LE(20, 6);
  central.writeUInt16LE(0, 10);
  central.writeUInt32LE(crc, 16);
  central.writeUInt32LE(content.length, 20);
  central.writeUInt32LE(content.length, 24);
  central.writeUInt16LE(name.length, 28);

  const localPart = Buffer.concat([local, name, content]);
  const centralPart = Buffer.concat([central, name]);

  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(1, 8);
  end.writeUInt16LE(1, 10);
  end.writeUInt32LE(centralPart.length, 12);
  end.writeUInt32LE(localPart.length, 16);

  return Buffer.concat([localPart, centralPart, end]);
}

function contentFor(name: string, mime: string): Buffer {
  if (mime === "application/pdf") return PDF(name);
  if (name.endsWith(".csv")) return CSV();
  if (name.endsWith(".md")) return MARKDOWN(name);
  if (name.endsWith(".ipynb")) return NOTEBOOK();
  if (name.endsWith(".zip") || name.endsWith(".xlsx")) return ZIP();

  return Buffer.from(`Placeholder file "${name}" from the Nexivora seed.\n`, "utf8");
}

/**
 * Write one object per storage key.
 *
 * Uses the same `groups/<id>/<key>` layout the local driver resolves, and the
 * same upload root, so a seeded file and an uploaded one are indistinguishable
 * to the file route — which is the point.
 */
export async function seedFileObjects(
  files: readonly { storageKey: string; name: string; mimeType: string }[],
  uploadDir: string,
): Promise<{ written: number; bytes: number; sizes: [string, number][] }> {
  const root = path.resolve(process.cwd(), uploadDir);
  const sizes: [string, number][] = [];
  let bytes = 0;

  for (const file of files) {
    const target = path.join(root, file.storageKey);
    await mkdir(path.dirname(target), { recursive: true });

    const content = contentFor(file.name, file.mimeType);
    await writeFile(target, content);

    sizes.push([file.storageKey, content.length]);
    bytes += content.length;
  }

  return { written: sizes.length, bytes, sizes };
}
