import { createHash } from "node:crypto";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { env } from "@/lib/env";

import type { StorageProvider, StoredObject } from "./provider";

/**
 * The local-disk driver.
 *
 * Files live **outside the web root** (`UPLOAD_DIR`, `./.uploads` by default,
 * gitignored) and are reachable only through `GET /api/files/[id]`, which
 * authorises before it streams. There is deliberately no static path: putting
 * uploads under `public/` would make every group's files world-readable to
 * anyone who could guess or leak a URL, and no amount of unguessable naming
 * turns that back into a permission.
 *
 * `resolve()` below is the load-bearing part. A storage key is generated by us
 * and is therefore trustworthy in principle, but "in principle" is how
 * traversal bugs happen: the resolved absolute path is asserted to sit inside
 * the upload root, so a key that ever became attacker-influenced still cannot
 * escape it.
 */

/**
 * The upload root, resolved on first use rather than at import.
 *
 * Module scope is the wrong place for it twice over: Next evaluates this module
 * while collecting page data at build time, where `process.cwd()` is the build
 * machine's directory and `UPLOAD_DIR` may not exist yet — and Turbopack's
 * static analysis sees a filesystem path derived from `cwd()` and traces the
 * **entire project** into the server bundle, which is what turned this from a
 * warning into a failed build.
 */
let cachedRoot: string | null = null;

function uploadRoot(): string {
  cachedRoot ??= path.resolve(/* turbopackIgnore: true */ process.cwd(), env.UPLOAD_DIR);
  return cachedRoot;
}

function resolve(key: string): string {
  const root = uploadRoot();

  // A key is generated by us, so in principle it is trustworthy — but "in
  // principle" is how traversal bugs happen. `path.join` normalises `..`, so
  // this comparison is made after any traversal has already been collapsed,
  // which is what makes it meaningful rather than decorative.
  // `turbopackIgnore` because this path is runtime data, never a module: the
  // bundler's static analysis cannot tell those apart, and its default guess —
  // trace the whole project into the server bundle — fails the build outright.
  const target = path.join(/* turbopackIgnore: true */ root, key);

  if (target !== root && !target.startsWith(root + path.sep)) {
    throw new Error("Storage key resolves outside the upload root.");
  }

  return target;
}

export const localStorage: StorageProvider = {
  name: "local",

  async put(key, data): Promise<StoredObject> {
    const target = resolve(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, data);

    return {
      key,
      sizeBytes: data.byteLength,
      checksum: createHash("sha256").update(data).digest("hex"),
    };
  },

  async get(key): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(resolve(key)));
    } catch {
      // A missing object is a null, not a throw: the caller's own
      // authorisation has already decided whether this person may know the
      // file exists, and a distinguishable error here would answer that
      // question a second time, differently.
      return null;
    }
  },

  async size(key): Promise<number | null> {
    try {
      return (await stat(resolve(key))).size;
    } catch {
      return null;
    }
  },

  async delete(key): Promise<void> {
    await rm(resolve(key), { force: true });
  },
};

/**
 * The driver in use.
 *
 * `r2` is declared in the env schema and deliberately not implemented — it is
 * a deferred item, and a stub that silently fell back to local would be worse
 * than a boot failure naming the gap.
 */
export function storage(): StorageProvider {
  if (env.STORAGE_DRIVER === "local") return localStorage;

  throw new Error(
    `STORAGE_DRIVER="${env.STORAGE_DRIVER}" has no driver yet. Only "local" is implemented — ` +
      "R2 is deferred until disk pressure appears (see PROGRESS.md, Deferred items).",
  );
}
